### ISSUE TITLE
Census builder failing due to Portal REST API response handling

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cell-census#161]
The latest main fails when requesting the Portal REST API (https://api.cellxgene.cziscience.com/curation/v1/collections) list of datasets:

```
2023-02-11 02:18:20 10969   INFO     Loading manifest from CELLxGENE data portal...
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/bruce/cell-census/tools/cell_census_builder/__main__.py", line 340, in <module>
    sys.exit(main())
  File "/home/bruce/cell-census/tools/cell_census_builder/__main__.py", line 83, in main
    cc = build(args, soma_path, assets_path, experiment_builders)
  File "/home/bruce/cell-census/tools/cell_census_builder/__main__.py", line 137, in build
    datasets = build_step1_get_source_assets(args, assets_path)
  File "/home/bruce/cell-census/tools/cell_census_builder/__main__.py", line 196, in build_step1_get_source_assets
    datasets = load_manifest(args.manifest)
  File "/home/bruce/cell-census/tools/cell_census_builder/manifest.py", line 145, in load_manifest
    datasets = load_manifest_from_CxG()
  File "/home/bruce/cell-census/tools/cell_census_builder/manifest.py", line 59, in load_manifest_from_CxG
    datasets = {
  File "/home/bruce/cell-census/tools/cell_census_builder/manifest.py", line 64, in <dictcomp>
    "dataset_title": dataset["title"],
KeyError: 'title'
```

This seems related to #126 but I'm not sure if the bug is in the builder or in the REST API (#126 suggests it is a Portal REST API bug).

CC: @brianraymor @Bento007

**Comment by atolopko-czi** [comment]
The dataset_title is returned by the _dataset_ API call, not the _collections_ API call. Turns out the builder manifest code looked for it in both places. The collection API response would never have this data, but it would later successfully be obtained from the dataset API call. We simply need to remove that line of code.
