### ISSUE TITLE
cell_census_builder in single-process mode will throw TileDB error in validation()

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cell-census#284]
A full census build, with config:
```
multi_process: false
max_workers: null
```

Will fail in during validation with a TileDB exception. This is reproducible only when running single-process - if the config is`multi_process: true`, which is the default, it works fine.  Am filing this bug as a tracking issue while I dig into the root cause and a reproducible test case.

Config:
```
tiledbsoma.__version__    1.0.0
tiledb.__version__        0.20.0
core version              2.14.0
python version            3.9.16.final.0
```

Example (using a recently built census which passes validation when config is `multi_process: true`:

```
$ python -m cell_census_builder ./tmp/census-build/ --test-resume
2023-03-23 03:09:46 3856721 INFO     Census build: start [version=0.10.1.dev29+ge40653a]
2023-03-23 03:09:46 3856721 INFO     CensusBuildArgs(working_dir=PosixPath('tmp/census-build'), config=CensusBuildConfig(verbose=1, log_dir='logs', log_file='build.log', consolidate=True, disable_dirty_git_check=True, cell_census_S3_path='s3://cellxgene-data-public/cell-census', build_tag='2023-03-22', multi_process=False, max_workers=None, host_validation_disable=False, host_validation_min_physical_memory=549755813888, host_validation_min_swap_memory=2199023255552, host_validation_min_free_disk_space=1099511627776, manifest=None, test_first_n=None), state=CensusBuildState(do_prebuild_set_defaults=True, do_prebuild_checks=True, do_build_soma=True, do_validate_soma=False, do_create_reports=True))
2023-03-23 03:09:46 3856721 INFO     Build step do_prebuild_set_defaults [1 of 5]: already complete, skipping.
2023-03-23 03:09:46 3856721 INFO     Build step do_prebuild_checks [2 of 5]: already complete, skipping.
2023-03-23 03:09:46 3856721 INFO     Build step do_build_soma [3 of 5]: already complete, skipping.
2023-03-23 03:09:46 3856721 INFO     Build step do_validate_soma [4 of 5]: start
2023-03-23 03:09:56 3856721 INFO     Validation start
2023-03-23 03:09:56 3856721 INFO     Loaded gene lengths external reference for homo_sapiens, 116092 genes.
2023-03-23 03:09:56 3856721 INFO     Loaded gene lengths external reference for mus_musculus, 116092 genes.
2023-03-23 03:10:02 3856721 INFO     validate_axis 1 of 503 complete.

...

2023-03-23 03:20:24 3856721 INFO     validate_axis 117 of 503 complete.
2023-03-23 03:20:24 3856721 CRITICAL Caught exception, exiting
Traceback (most recent call last):
  File "/home/bruce/cell-census/tools/cell_census_builder/src/cell_census_builder/__main__.py", line 70, in do_build
    if not build_step(args):
  File "/home/bruce/cell-census/tools/cell_census_builder/src/cell_census_builder/__main__.py", line 123, in do_validate_soma
    if not validate_a_soma(args):
  File "/home/bruce/cell-census/tools/cell_census_builder/src/cell_census_builder/build_soma/validate_soma.py", line 568, in validate
    assert (eb_info := validate_axis_dataframes(assets_path, soma_path, datasets, experiment_specifications, args))
  File "/home/bruce/cell-census/tools/cell_census_builder/src/cell_census_builder/build_soma/validate_soma.py", line 223, in validate_axis_dataframes
    for eb_name, ebi in _validate_axis_dataframes(
  File "/home/bruce/cell-census/tools/cell_census_builder/src/cell_census_builder/build_soma/validate_soma.py", line 145, in _validate_axis_dataframes
    census_data = census[CENSUS_DATA_NAME]
  File "/home/bruce/cell-census/venv/lib/python3.9/site-packages/tiledbsoma/_collection.py", line 343, in __getitem__
    entry.soma = _factory._open_internal(
  File "/home/bruce/cell-census/venv/lib/python3.9/site-packages/tiledbsoma/_factory.py", line 142, in _open_internal
    handle = opener(uri, mode, context, timestamp)
  File "/home/bruce/cell-census/venv/lib/python3.9/site-packages/tiledbsoma/_tdb_handles.py", line 85, in open
    tdb = cls._opener(uri, mode, context, timestamp_ms)
  File "/home/bruce/cell-census/venv/lib/python3.9/site-packages/tiledbsoma/_tdb_handles.py", line 224, in _opener
    uri, mode, ctx=_group_timestamp_ctx(context.tiledb_ctx, timestamp)
  File "/home/bruce/cell-census/venv/lib/python3.9/site-packages/tiledbsoma/_tdb_handles.py", line 238, in _group_timestamp_ctx
    return tiledb.Ctx(group_cfg)
  File "/home/bruce/cell-census/venv/lib/python3.9/site-packages/tiledb/ctx.py", line 345, in __init__
    super().__init__(_config)
tiledb.cc.TileDBError: [TileDB::C++API] Error: Failed to create context
```

**Comment by bkmartinjr** [comment]
Root cause and work-around identified.  See: single-cell-data/TileDB-SOMA#1169
